# Generated by Django 3.2.19 on 2023-10-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
    ]
